name: Release Handler

on:
  release:
    types:
      - published
      - prereleased
      - released
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version to use.'
        required: true
        type: string

permissions:
  contents: write

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-release-info:
    name: Get version number
    uses: ./.github/workflows/[R] - get-info-from-release.yml
    with:
      releaseName: ${{ inputs.version || github.event.release.name }}

  publish-to-steam:
    name: Publish to Steam
    uses: ./.github/workflows/[R] - publish-to-steam.yml
    needs:
      - get-release-info
    strategy:
      matrix:
        environment:
          - production
    with:
      environment: ${{ matrix.environment }}
      repository: ${{ github.repository }}
      steamReleaseBranch: ${{ needs.get-release-info.outputs.releaseBranch }}
      versionNumber: ${{ needs.get-release-info.outputs.versionNumber }}
      zipPrefix: 'Debug'
    secrets:
      steamBuildConfigVDF: ${{ secrets.STEAM_BUILD_CONFIG_VDF }}
      steamBuildUsername: ${{ secrets.STEAM_BUILD_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
