name: Release Handler

on:
  release:
    types:
      - published
      - prereleased
      - released
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version to use.'
        required: true
        type: string

permissions:
  contents: write

concurrency:
  group: ci-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-release-info:
    name: Get version number
    uses: ./.github/workflows/[R] - get-info-from-release.yml
    with:
      releaseName: ${{ inputs.version || github.event.release.name }}

  publish-to-steam:
    name: Publish to Steam
    uses: ./.github/workflows/[R] - publish-to-steam.yml
    needs:
      - get-release-info
    strategy:
      matrix:
        environment:
          - production
    with:
      environment: ${{ matrix.environment }}
      repository: ${{ github.repository }}
      steamBuildUsername: ${{ vars.STEAM_BUILD_USERNAME }}
      steamReleaseBranch: ${{ needs.get-release-info.outputs.releaseBranch }}
      versionNumber: ${{ needs.get-release-info.outputs.versionNumber }}
      zipPrefix: 'Debug'
    secrets:
      steamBuildConfigVDF: ${{ secrets.STEAM_BUILD_CONFIG_VDF }}
      token: ${{ secrets.GITHUB_TOKEN }}

  publish-to-itch:
    name: Publish to Itch
    uses: ./.github/workflows/[R] - publish-to-itch.yml
    needs:
      - get-release-info
    strategy:
      matrix:
        platform:
          - alias: linux
            arch: x64
            name: linux
          - alias: osx
            arch: universal
            name: darwin
          - alias: windows
            arch: x64
            name: win32
    with:
      itchioAppID: ${{ vars.ITCHIO_APP_ID }}
      itchioUsername: ${{ vars.ITCHIO_USERNAME }}
      platformAlias: ${{ matrix.platform.alias }}
      platformArch: ${{ matrix.platform.arch }}
      platformName: ${{ matrix.platform.name }}
      versionNumber: ${{ needs.get-release-info.outputs.versionNumber }}
      zipPrefix: 'Debug'
    secrets:
      itchioButlerAPIKey: ${{ secrets.ITCHIO_BUTLER_API_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
