name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ci-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-release-info:
    name: Get version number
    uses: ./.github/workflows/reusable/get-info-from-release.yml
    with:
      releaseName: ${{ github.event.release.name }}

  publish-to-steam:
    name: Publish to Steam
    uses: ./.github/workflows/reusable/publish-to-steam.yml
    needs:
      - get-release-info
    strategy:
      matrix:
        environment:
          - production
    with:
      environment: ${{ matrix.environment }}
      repository: ${{ github.repository }}
      steamReleaseBranch: ${{ needs.get-release-info.outputs.releaseBranch }}
      versionNumber: ${{ needs.get-release-info.outputs.versionNumber }}
      zipPrefix: 'Debug'
    secrets:
      steamBuildConfigVDF: ${{ secrets.STEAM_BUILD_CONFIG_VDF }}
      steamBuildUsername: ${{ secrets.STEAM_BUILD_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
